// Массив с вопросами. Не Зашифрован :)


let allQuestions = [
    // Цена 100
    {
        type: 0,
        price: 100,
        text: 'Какой язык используется для структурирования веб-страниц?',
        image: false,
        answers: ['HTML', 'Python', 'C++', 'JavaScript'],
        correctAnswer: [0],
        answered: null,
    },
    {
        type: 1,
        price: 100,
        text: 'Какие из этих программ являются антивирусами?',
        image: false,
        answers: ['Windows Defender', 'Adobe Photoshop', 'Norton Security', 'Avast', 'Microsoft Word'],
        correctAnswer: [0, 2, 3],
        answered: null,
    },
    {
        type: 2,
        price: 100,
        text: 'Заполните пропуски:',
        textDd: "Оперативная память компьютера известна как |. Для подключения к интернету часто используется |.",
        answers: [['RAM', 'ROM', 'CPU'], ['Wi-Fi', 'USB', 'HDMI']],
        correctAnswer: [0, 0],
        answered: null,
    },
    // Цена 150
    {
        type: 0,
        price: 150,
        text: 'Какой компонент компьютера отвечает за обработку данных?',
        image: false,
        answers: ['Жесткий диск', 'Оперативная память', 'Процессор', 'Видеокарта'],
        correctAnswer: [2],
        answered: null,
    },
    {
        type: 1,
        price: 150,
        text: 'Выберите программы для создания презентаций:',
        image: false,
        answers: ['Microsoft Word', 'Adobe Illustrator', 'Microsoft PowerPoint', 'Google Slides', 'Notepad'],
        correctAnswer: [2, 3],
        answered: null,
    },
    {
        type: 2,
        price: 150,
        text: 'Заполните пропуски:',
        textDd: "Файлы с расширением .xls обычно открываются в |. | - это популярная поисковая система.",
        answers: [['Microsoft Excel', 'Microsoft Word', 'Adobe Reader'], ['Google', 'Bing', 'Yahoo']],
        correctAnswer: [0, 0],
        answered: null,
    },
    // Цена 200
    {
        type: 0,
        price: 200,
        text: 'Какая технология используется для безопасного обмена данными в интернете?',
        image: false,
        answers: ['SSL', 'FTP', 'HTTP', 'TCP'],
        correctAnswer: [0],
        answered: null,
    },
    {
        type: 1,
        price: 200,
        text: 'Какие из этих компонентов являются частями материнской платы?',
        image: false,
        answers: ['RAM', 'Процессор', 'Монитор', 'Чипсет', 'Жесткий диск'],
        correctAnswer: [0, 1, 3],
        answered: null,
    },
    {
        type: 2,
        price: 200,
        text: 'Заполните пропуски:',
        textDd: "Для создания веб-сайтов используется язык |. Главная страница сайта часто называется |.",
        answers: [['HTML', 'Python', 'Java'], ['homepage', 'index', 'main']],
        correctAnswer: [0, 1],
        answered: null,
    },
    {
        type: 0,
        price: 200,
        text: 'Какой из следующих терминов обозначает вредоносное ПО, скрытое в законных программах?',
        image: false,
        answers: ['Троян', 'Вирус', 'Спам', 'Шпионское ПО'],
        correctAnswer: [0],
        answered: null,
    },
    {
        type: 1,
        price: 200,
        text: 'Выберите элементы, которые относятся к аппаратному обеспечению компьютера:',
        image: false,
        answers: ['Операционная система', 'Процессор', 'Microsoft Office', 'Видеокарта', 'Браузер'],
        correctAnswer: [1, 3],
        answered: null,
    },
    {
        type: 2,
        price: 200,
        text: 'Заполните пропуски:',
        textDd: "Формат | обычно используется для сжатия видео. Для удаления файла без возможности восстановления используется клавиша |.",
        answers: [['MP4', 'JPEG', 'DOCX'], ['Shift+Delete', 'Ctrl+Delete', 'Alt+Delete']],
        correctAnswer: [0, 0],
        answered: null,
    },
    // Цена 250
    {
        type: 0,
        price: 250,
        text: 'Что такое алгоритм в контексте информатики?',
        image: false,
        answers: ['Устройство для обработки данных', 'Набор инструкций для решения задачи', 'Тип компьютерной программы', 'Код ошибки'],
        correctAnswer: [1],
        answered: null,
    },
    {
        type: 1,
        price: 250,
        text: 'Идентифицируйте устройства, способные преобразовать аналоговые или цифровые сигналы в машинный код, тем самым осуществляя процесс ввода информационных данных в систему центральной обработки данных (ЦОД)',
        image: false,
        answers: ['Устройство визуального отображения данных', 'Электромеханический трансдьюсер для манипуляции символами', 'Механизм электростатической печати', 'Оптоэлектронное устройство сканирования графических и текстовых данных', 'Акустическое устройство для вывода звуковых сигналов'],
        correctAnswer: [1, 3],
        answered: null,
    },
    {
        type: 2,
        price: 250,
        text: 'Заполните пропуски:',
        textDd: "URL обозначает |. Основной функцией операционной системы является |.",
        answers: [['Uniform Resource Locator', 'User Role Login', 'Ultimate RAM Load'], 
                  ['управление программами', 'хранение данных', 'защита от вирусов']],
        correctAnswer: [0, 0],
        answered: null,
    },
    // Цена 300
    {
        type: 0,
        price: 300,
        text: 'Как называется процесс поиска и устранения ошибок в программном коде?',
        image: false,
        answers: ['Компиляция', 'Отладка', 'Шифрование', 'Декомпиляция'],
        correctAnswer: [1],
        answered: null,
    },
    {
        type: 1,
        price: 300,
        text: 'Выберите из списка устройства хранения данных:',
        image: false,
        answers: ['RAM', 'Процессор', 'SSD', 'Мышь', 'Жесткий диск'],
        correctAnswer: [2, 4],
        answered: null,
    },
    {
        type: 2,
        price: 300,
        text: 'Заполните пропуски:',
        textDd: "Для создания компьютерных игр часто используется движок |. Система | используется в Apple компьютерах.",
        answers: [['Unity', 'Unreal', 'CryEngine'], ['macOS', 'Windows', 'Linux']],
        correctAnswer: [0, 0],
        answered: null,
    }
    // Дополните оставшимися вопросами аналогичным образом, соблюдая простоту и доступность.
];


